stages:
  - build
  - deploy


build-job:
    stage: build
    script:
     - docker build -t webpictweak ./WebPicTweak/
     - docker build -t client ./WebPicTweak/tweaksite/
     - docker build -t nginx:mainline

deploy-job:
    stage: deploy
    script:
     - docker compose up -d