stages:
  - build
  - deploy

variables:
  DEPLOY_USER: "mori"
  DEPLOY_SERVER: "79.133.182.202"
  DEPLOY_PATH: "/home/mori/PTW/"
  DEPLOY_PORT: "3273"

build:
  stage: build
  image: docker:latest
  script:
    - docker compose build



deploy:
  stage: deploy
  image: alpine:latest
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always
  before_script:
    - apk add --no-cache openssh-client git bash
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -p $DEPLOY_PORT -H $DEPLOY_SERVER >> ~/.ssh/known_hosts
  script:
    - ssh -p $DEPLOY_PORT $DEPLOY_USER@$DEPLOY_SERVER "cd $DEPLOY_PATH && git pull && docker compose up -d"

  