version: '3.4'

services:
  backend:
    image: ${DOCKER_REGISTRY-}webpictweak
    build:
      context: .
      dockerfile: WebPicTweak/Dockerfile
        

  client:
    image: client
    build:
      context: ./tweaksite/
      dockerfile: Dockerfile
  
  init-dhparams:
    image: certbot/certbot
    entrypoint: /bin/sh
    command: -c 'test -f /etc/letsencrypt/ssl-dhparams.pem || openssl dhparam -out /etc/letsencrypt/ssl-dhparams.pem 4096'
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt

  proxy:
    image: docker.io/library/nginx
    entrypoint: /bin/sh
    command: -c 'while :; do sleep 6h && wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'
    ports:
      - 4040:80
    depends_on:
      init-dhparams:
        condition: service_completed_successfully
        required: true
      certbot-oneshot:
        condition: service_completed_successfully
        required: true
    volumes:
      - cert_volume:/etc/letsencrypt:ro
      - acme_challenge:/usr/share/nginx/html/.well-known
      - react_build:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  certbot-oneshot:
    image: docker.io/certbot/certbot
    restart: "no"
    entrypoint: /bin/sh
    command: -c 'test -d /etc/letsencrypt/live/${BASE_DOMAIN:-example.ru} || certbot certonly --staging --standalone --register-unsafely-without-email -d "${BASE_DOMAIN:-example.ru}" --rsa-key-size ${rsa_key_size:-2048} --agree-tos --force-renewal'
    environment:
      - BASE_DOMAIN=tweakypro.ru
      - rsa_key_size=4096
    ports:
      - 80:80
    volumes:
      - cert_volume:/etc/letsencrypt

  certbot:
    image: certbot/certbot
    entrypoint: /bin/sh
    command: -c 'trap exit TERM; while :; do certbot renew --quiet; sleep 24h; done;'
    depends_on:
      proxy:
        condition: service_started
        required: true
    volumes:
      - cert_volume:/etc/letsencrypt
      - acme_challenge:/usr/share/nginx/html:rw

volumes:
  cert_volume: {}
  acme_challenge: {}
  react_build: {}


