version: '3.4'

services:
  backend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - BASE_DOMAIN=tweakypro.ru
      - STAND=prod
      - scheme=https
      - host=tweakypro.ru
      - remote_addr=127.0.0.1
      - uri=/
      - request_uri=/
      - proxy_add_x_forwarded_for=127.0.0.1
    ports:
      - "5000:8080"
      - "5001:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
   
  client: 
     ports:
      - "5002:3000"

  proxy:
     depends_on:
       - backend
       - client
     ports:
       - "4040:80"
     configs:
      - source: nginx-defaultserver
        target: /etc/nginx/conf.d/default.conf