// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebPicTweak.Infrastructure;

#nullable disable

namespace WebPicTweak.Infrastructure.Migrations
{
    [DbContext(typeof(LogDbContext))]
    [Migration("20250927135312_move to logs scheme")]
    partial class movetologsscheme
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Logs")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebPicTweak.Core.Models.Log.ImageLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("HasMetadata")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("SpentTime")
                        .HasColumnType("double precision");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("WidthHeight")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("UserId");

                    b.ToTable("ImageLogs", "Logs");
                });

            modelBuilder.Entity("WebPicTweak.Core.Models.Log.SessionLog", b =>
                {
                    b.Property<Guid>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAuthorized")
                        .HasColumnType("boolean");

                    b.Property<string>("PathToZip")
                        .HasColumnType("text");

                    b.Property<DateTime>("SessionCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("SpentTime")
                        .HasColumnType("double precision");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("SessionId");

                    b.HasIndex("UserId");

                    b.ToTable("SessionLogs", "Logs");
                });

            modelBuilder.Entity("WebPicTweak.Core.Models.Log.UserLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users", "Logs");
                });

            modelBuilder.Entity("WebPicTweak.Core.Models.Log.ImageLog", b =>
                {
                    b.HasOne("WebPicTweak.Core.Models.Log.SessionLog", "Session")
                        .WithMany("ProcessedFiles")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebPicTweak.Core.Models.Log.UserLog", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebPicTweak.Core.Models.Log.SessionLog", b =>
                {
                    b.HasOne("WebPicTweak.Core.Models.Log.UserLog", "User")
                        .WithMany("SessionLog")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("WebPicTweak.Core.Models.Image.ModifierOptions", "Options", b1 =>
                        {
                            b1.Property<Guid>("SessionLogSessionId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Compress")
                                .HasColumnType("integer")
                                .HasColumnName("Compress");

                            b1.Property<bool>("RemoveEXIF")
                                .HasColumnType("boolean")
                                .HasColumnName("RemoveEXIF");

                            b1.Property<int>("SizeScale")
                                .HasColumnType("integer")
                                .HasColumnName("SizeScale");

                            b1.HasKey("SessionLogSessionId");

                            b1.ToTable("SessionLogs", "Logs");

                            b1.WithOwner()
                                .HasForeignKey("SessionLogSessionId");
                        });

                    b.Navigation("Options")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebPicTweak.Core.Models.Log.SessionLog", b =>
                {
                    b.Navigation("ProcessedFiles");
                });

            modelBuilder.Entity("WebPicTweak.Core.Models.Log.UserLog", b =>
                {
                    b.Navigation("SessionLog");
                });
#pragma warning restore 612, 618
        }
    }
}
